[package]
name = "gamezap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.3"
sdl2 = "0.35.2"
ash-bootstrap = {git = "https://github.com/brandonpollack23/ash-bootstrap.git"}